CREATE TABLE IF NOT EXISTS edts (
    IDEdt INT AUTO_INCREMENT PRIMARY KEY,
    IDSalle VARCHAR(10),
    IDNiveaux VARCHAR(5),
    IDParcours VARCHAR(5),
    IDCreneaux INT,
    IDMatiere VARCHAR(10),
    cinEns VARCHAR(14),
    FOREIGN KEY (IDSalle) REFERENCES salles(IDSalle) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (IDNiveaux) REFERENCES niveaux(IDNiveaux) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (IDParcours) REFERENCES parcours(IDParcours) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (IDCreneaux) REFERENCES creneaux(IDCreneaux) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (IDMatiere) REFERENCES matieres(IDMatiere) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (cinEns) REFERENCES enseignants(cinEns)  ON DELETE CASCADE ON UPDATE CASCADE
);